name: Run Tests
on:
  push:
    branches:
      - '**'

jobs:
  run-all-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run custom test runner
        run: mvn test
