name: Build Windows Installer

on:
  workflow_dispatch:

jobs:
  package-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 22

      - name: Build fat JAR with Maven
        run: mvn clean package

      - name: Create custom runtime 
        run: |
          jlink.exe ^
            --output custom-runtime ^
            --add-modules java.base,java.desktop ^
            --strip-debug --no-header-files --no-man-pages ^
            --verbose
        shell: cmd

      - name: Package app with jpackage
        run: |
          jpackage.exe ^
            --input target ^
            --name Especialista ^
            --main-jar java-expert-0.0.1-jar-with-dependencies.jar ^
            --main-class org.javaexpert.Main ^
            --type app-image ^
            --app-version 1.0.0 ^
            --runtime-image custom-runtime
        shell: cmd
      
      - name: Upload App as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Especialista
          path: Especialista
